name: rampart-template
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.73
  - blast=2.7.1
  - minimap2=2.11
  - numpy=1.16
  - pandas=0.23.0=py36_1
  - pip=19.1
  - python=3.6.6
  - racon=1.3.3 #change to my version
  - snakemake=5.4.3
  - pip:
    - msgpack==0.5.6
    - binlorry==0.1
    - git+https://github.com/artic-network/Porechop.git